const DIC_ZH = {
  connectWallet: "连接钱包",
  currentAccountAddress: "当前账户地址",
  nftTypePlaceholder: "所有类型",
  nftSortPlaceholder: "排序",
  rent: "市场",
  lend: "出租",
  dashboard: "个人中心",
  faq: "常见问题解答",
  notion: "合约经过了彻底的测试和同行评审，但没有经过审计。使用风险自理。",
  dashToggleTitle: ["已经租入", "正在出租"],
  contractAddress: "合约地址",
  appVersion: "当前版本",
  toggleInfo: "请连接小狐狸钱包!",
  cancel: "取消",
  lendAll: "全部出租",
  selected: "已选中",
  items: "个宝贝",
  address: "合约地址",
  tokenId: "NFT编号",
  dailyRentPrice: "每天的租金",
  duration: "最长租期 (天)",
  collateral: "缴纳抵押金（eth）",
  totalRentPrice: "共计：",
  metas: [
    "合约地址",
    "NFT编号",
    "执行标准",
    "租金（eth/天）",
    "最长租期 (天)",
    "缴纳抵押金（eth）",
  ],
  rentNow: "马上租",
  lendNow: "马上出租",
  approvePaymentTokens: "确认支付",
  repay: "确认归还",
  inPoolUpdate: "更新租赁信息",
  inPoolWithdrw: "撤销租赁",
  claim: "超时认领补偿",
  rented: "主动归还",
  landed: "正在出租",
  searchHolder: "请输入tokenId或者关键词进行模糊匹配",
  lendEdit: "出租信息更新",
  lendDialogTitle: "确认出租信息",
  repayDialogTitle: "即将归还",
  outOfTime: "超时，无法归还",
  confirmLend: "确认授权平台挂单",
  confirmRent: "确认租借信息",
  isApproving: "请求已发起",
};
const DIC_EN = {
  connectWallet: "CONNECT WALLET",
  currentAccountAddress: "CURRENT ACCOUNT ADDRESS",
  nftTypePlaceholder: "ALL NFTS",
  nftSortPlaceholder: "SORT BY",
  rent: "RENT",
  lend: "LEND",
  dashboard: "DASHBOARD",
  faq: "FAQ",
  notion:
    "Contracts have been thoroughly tested and peer reviewed, but not audited. Use at your own risk.",
  dashToggleTitle: ["RENTED", "LENDING"],
  contractAddress: "Contract on etherscan",
  appVersion: "App version",
  toggleInfo: "Please connect your wallet!",
  cancel: "Cancel",
  lendAll: "Lend All",
  selected: "Selected",
  items: "Items",
  address: "Rivermen Contact Address",
  tokenId: "TokenId",
  dailyRentPrice: "Daily rent price",
  duration: "Max duration [days]",
  collateral: "collateral[eth]",
  metas: [
    "Address",
    "Token id",
    "Standard",
    "Daily price[per day][eth]",
    "Max duration [days]",
    "Collateral [per item][eth]",
  ],
  rentNow: "Rent now",
  lendNow: "Lend now",
  approvePaymentTokens: "Approve Rent",
  totalRentPrice: "Total RentPrice",
  repay: "Repay",
  inPoolUpdate: "Update",
  inPoolWithdrw: "Withdraw",
  claim: "Claim",
  rented: "repay",
  landed: "landed",
  searchHolder: "please input tokenId or name to search",
  lendEdit: "Edit Rent Info",
  lendDialogTitle: "Submit Rent Info",
  repayDialogTitle: "Repay",
  outOfTime: "Out of Time!",
  confirmLend: "Lend Now",
  confirmRent: "Approve & Confirm",
  isApproving: "Pending",
};
export { DIC_ZH, DIC_EN };
